### ISSUE TITLE
remove the cursing

### ISSUE THREAD

**Issue by thintheserverowner** [CammiePone/Arcanus#10]
plz remove the cursing from this [advancements.arcanus.discombobulate.title]
[
a person in my server doest like peeps cursing

**Comment by CammiePone** [comment]
you can use a resource pack to change it, I'm keeping the meme in

**Comment by CammiePone** [comment]
nvm you're getting your wish, AOF said, for the sake of streamers, it would probably best to remove it, so I'll do that sometime tomorrow
