### ISSUE TITLE
[Compatibility] Better Strongholds

### ISSUE THREAD

**Issue by itsdinkd** [CammiePone/Arcanus#12]
Please make mod compatible with YUNG's Better Strongholds as this replaces vanilla strongholds and looks like its not putting the spell books in the loot table

Love the mod btw!!!!

**Comment by CammiePone** [comment]
It already does

**Comment by itsdinkd** [comment]
Weird because I went through every single chest and there was not one spellbook.

**Comment by CammiePone** [comment]
Were they chests in the library part of the structure? 'Cause that's where it would spawn. Also some bookshelves should be replaced with Arcanus' fillable ones.

**Comment by itsdinkd** [comment]
I will double check.

will this work with modded villages library? ie; Stonehelm?

**Comment by CammiePone** [comment]
I would hope so, since that's one of the mods with support out of the box. You can find all the structures that should get modified in the config file, as well as add new ones that have bookshelves or lecterns using a command from Mesh
