### ISSUE TITLE
"Could Not Find Required Mod"?

### ISSUE THREAD

**Issue by wynternight** [CammiePone/Arcanus#17]
Hello. Apologies, I'm new to modding Minecraft.

I've installed the Fabric API and Arcanus into the Mods folder, but when I launch it, I get an error message that reads:

"Could not find required mod: arcanus requires {trinkets @ [>3.0.4]}
--Creating empty clause ?"

This is the first time I'm using Fabric, so I'm not sure where the issue is. I've redownloaded and reinstalled everything twice but the issue persists. Any wisdom is appreciated; I'm probably missing something obvious.

Thanks much.

**Comment by CammiePone** [comment]
You need Trinkets.

**Comment by wynternight** [comment]
Okay, thank you. I've never heard of Trinkets before now.
