### ISSUE TITLE
The game crashes when I break the display case in which the staff is located

### ISSUE THREAD

**Issue by ghost** [CammiePone/Arcanus#18]
The game crashes with an error code of 0 and there is no crash report itself, and by the way it does not matter what kind of staff will be in the display case

Mods: Additional Additions 2.1.3, Air Strafing attribute 1.2, antique atlas 6.1.0, Arcanus 1.16, Architectury API 2.5.30, BCLib 0.3.1, Better End 0.11.0-pre, Better Nether 5.1.3, BeWitchment 1.17-9, Bountiful 1.0.0, Cardinal Components API 3.1.1, Cloth Config 5.0.38, Extra Origins 1.17-8, Fabric API 0.40.1, Fabric Language Kotlin 1.6.5+kotlin.1.5.31, Fabrilous Updater 2.4, Illuminations 1.8, Impersonate 2.3.5, Indium 1.0.0, Kambrik, Medieva Weapons 1.1.7, Mermod 1.9, Mob Origins 1.7.0, Mod Menu 2.0.14, Origins 1.1.1, Origins Classes 1.2.2, pal 1.3.0, Patchouli 1.17-54-FABRIC, Pehkui 2.4.0+1.14.4, reeses sodium options 1.2.0, REI 6.0.279-alpha, Shadekin Origin 2.0, Sit 1.17.1-13, Sodium Extra 0.3.5, Sodium 0.3.2 Build 7, Somnus API 0.0.14, Trinkets 3.0.4, Visuality 0.1.3, Fabric Waystones 2.1.2.

Version: 1.17.1
Fabric Version: fabric-loader-0.11.7-1.17.1
Dedicated RAM to Minecraft: 5 Gb
Platform: Windows 10 Home
Launcher: Official Minecraft Launcher

**Comment by CammiePone** [comment]
Okay, just wanna say that this is almost a perfect bug report. You gave me the game version, your mod versions, your Fabric version, it's great.

The only thing I need is a regular log, even if it might not be super useful. Error code 0 just means the application crashed, and while the lack of crash report is annoying, it's not the worst thing in the world since the log usually will contain something

**Comment by ghost** [comment]
Where i can find this log file? Or how i can create this log file with these an error?

> Okay, just wanna say that this is almost a perfect bug report. You gave me the game version, your mod versions, your Fabric version, it's great.
> 
> The only thing I need is a regular log, even if it might not be super useful. Error code 0 just means the application crashed, and while the lack of crash report is annoying, it's not the worst thing in the world since the log usually will contain something

**Comment by CammiePone** [comment]
Folder your mods folder is in should have two other folders:
One called logs (inside should be a text file called latest.log)
And one called crash-reports (want the one with the latest date)

Make sure the last time you played AND crashed was when you caused thie crash to occur

**Comment by ghost** [comment]
Okay, one moment and i am send you two these files

**Comment by ghost** [comment]
https://bytebin.lucko.me/GUowCO0VEe

**Comment by ghost** [comment]
> https://bytebin.lucko.me/GUowCO0VEe

These a crash log file

**Comment by ghost** [comment]
https://bytebin.lucko.me/dz27SiiypN

And this is latest.log

**Comment by CammiePone** [comment]
Try removing Sodium and repeating the crash

**Comment by ghost** [comment]
> Try removing Sodium and repeating the crash

Yes, this is a problem with Sodium mod, the crash is no longer appear

**Comment by CammiePone** [comment]
Not sure if it's Sodium's fault, just that Sodium may be causing it to appear. I'll test some more to see

**Comment by ghost** [comment]
Okay, thanks for the help

**Comment by CammiePone** [comment]
should be fixed now
