### ISSUE TITLE
Arcanus Crashed My Game

### ISSUE THREAD

**Issue by toErIpNid** [CammiePone/Arcanus#2]
I added it into my modpack and it no work. 

MC Version: 1.17.1
Arcanus Version: 1.0.
Fabric Version: 0.11.6

Log: 
[crash-2021-08-19_19.14.19-client.txt](https://github.com/CammiePone/Arcanus/files/7018297/crash-2021-08-19_19.14.19-client.txt)

**Comment by toErIpNid** [comment]
Luv u cam

**Comment by CammiePone** [comment]
love you too bb <3
