### ISSUE TITLE
Forcing Modloader 0.12

### ISSUE THREAD

**Issue by itsdinkd** [CammiePone/Arcanus#22]
probably shouldn't force 0.12 as a required dependency. its not even fully supported for public use yet, it's in testing. you will not find version 0.12 in any launcher

![image](https://user-images.githubusercontent.com/35115304/137053991-5bddea83-59ce-4596-8194-5f0e722502c9.png)

![image](https://user-images.githubusercontent.com/35115304/137053874-6122046d-6a91-40f2-974d-9de2429cd3ed.png)

**Comment by AmonRay** [comment]
true, I was also surprised when I saw such an dependency

**Comment by CammiePone** [comment]
It was done in Upcraft's PR to fix an issue with Arcanus on 0.12.0, and he wasnt sure if the fix would work on 0.11.0, so he did the cautious thing and made it 0.12.0 only.

I forgot about this though when updating so it is what it is for now.

**Comment by itsdinkd** [comment]
If I change dependency in the fabric json to 0.11.7, is anything going to break?  No one can use 12.0 on CurseForge launcher, which majority use, meaning no use in any modpacks.    From: CammieSent: Thursday, October 14, 2021 6:39 PMTo: CammiePone/ArcanusCc: red2blue; AuthorSubject: Re: [CammiePone/Arcanus] Forcing Modloader 0.12 (#22) It was done in Upcraft's PR to fix an issue with Arcanus on 0.12.0, and he wasnt sure if the fix would work on 0.11.0, so he did the cautious thing and made it 0.12.0 only.I forgot about this though when updating so it is what it is for now.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CammiePone** [comment]
I think it's okay to use a dependency override for it, but I haven't thoroughly tested yet myself. AOF4 is likely going to use a dependency override, so we'll find out
