### ISSUE TITLE
Crash when doing something stupid with the Origins mod

### ISSUE THREAD

**Issue by Venaf** [CammiePone/Arcanus#24]
[crash-2021-10-22_19.12.37-server.txt](https://github.com/CammiePone/Arcanus/files/7401790/crash-2021-10-22_19.12.37-server.txt)
So what I did was cast magic missile while using the Phasing ability (which lets you walk inside blocks without suffocating).  I was curious if it would collide immediately or continue out of the block I was in, but what it did was hit me and then crash the game; now the game crashes on load with this log.
[crash-2021-10-22_19.15.19-server.txt](https://github.com/CammiePone/Arcanus/files/7401796/crash-2021-10-22_19.15.19-server.txt)

A real edge case, I'm sure, but maybe something worth looking at if it's Arcanus doing it and it's a general issue with hitting yourself with your own spell.

**Comment by CammiePone** [comment]
Can I ask you to upload both of those crashes to pastebin?

**Comment by Venaf** [comment]
> Can I ask you to upload both of those crashes to pastebin?

Absolutely.  First one: https://pastebin.com/YiVYf53H

Second one: https://pastebin.com/d21uEn6a

**Comment by CammiePone** [comment]
hah okay I think I know why this is happening, I'll fix it today
