### ISSUE TITLE
IO netty error Memory overflow issue

### ISSUE THREAD

**Issue by AltimusX** [CammiePone/Arcanus#27]
https://paste.ee/p/jxVfe

I get IO netty disconnections when I try to make a world with this loaded on, my worlds load just fine without it. I have lots of mods and I am not sure what mod is causing the memory overflow crash, when this mod is added. Even with new worlds, as demonstrated with this paste.ee link.

**Comment by CammiePone** [comment]
You just have too many mods. Install XL Packets
https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric
