### ISSUE TITLE
[Question] Arcane Barrier Spell Book

### ISSUE THREAD

**Issue by BluGlu** [CammiePone/Arcanus#28]
I wanted to ask about this spell's book, is it only obtainable through creative or is there another way?

**Comment by CammiePone** [comment]
It can be found just like any other spell book

**Comment by BluGlu** [comment]
well, I have travelled for you know a while(about 10 libraries or so) and I haven't found any, at all so that's why I even made this post in the first place. So what do you mean exactly by "found just like any other book"? like from villages or from some special structure?

**Comment by CammiePone** [comment]
Just from villages, yea
