### ISSUE TITLE
incompatibility with terralith (overworld generation mod)

### ISSUE THREAD

**Issue by TheRanker** [CammiePone/Arcanus#31]
with using arcanus in a modpack along with terralith... we lose terralith world generation and get vanilla.
remove arcanus and terralith generates properly. 

unsure if this is something that can be fixed.  as terralith is incompatible with any biome generation mod.

**Comment by CammiePone** [comment]
I'm not touching biomes, so uh...

**Comment by CammiePone** [comment]
anyways, can you give me more information, such as the version of Terralith you're using, the version of Arcanus you're using, etc?

**Comment by TheRanker** [comment]
Terralith v2.0.1a ~ Fabric.jar

arcanus-1.24.jar

doing more testing .. isolating the issues.. as there are a few mods that are stopping the generation of terralith.  i created fabric profile for 1.18 and only added arcanus and terralith. testing a few possilbiitiles..  may be a 3rd mod interaction here too within my modpack im working on developing.  be a minute and ill see if i can get you some more info

**Comment by TheRanker** [comment]
works with just the mod and terralith.. biomes generate.. so it mus tgbe somethign else... ill keep looking. .sorry for wasting time.. but i did remove arcanus.. i got biomes.. added it.. i lost them... but seems to be otehr mods and more troubleshooting on my side to fix it up.

**Comment by CammiePone** [comment]
Hm... alright, well hopefully you are able to find out the cause of the interaction. Afaik the only world gen Arcanus touches is a structure processor for bookshelves and lecterns, which _shouldn't_ cause any problems.
