### ISSUE TITLE
[1.17] Corrupted character?

### ISSUE THREAD

**Issue by Zarvera** [CammiePone/Arcanus#32]
Hi, been playing Benchmark pack recently and seems to have managed to corrupt my character practically as soon as i've tried interacting with the mod.
I already had a couple of books by that point, so i've made a wand, did a few r-clicks (R-R-R i believe?) which displayed "Lunge" text though i haven't moved or noticed any effect besides half-drained mana bar displaying permanently. It was late so i went to sleep, next day i tried casting "Dream Warp" which damaged me significantly, mana bar now had several red orbs instead, no effect was produced besides a message that i "feel worn out". Worst of all is that mana does not regens in any way and it locked my health regen permanently too, no matter how full i am health never restores, dying doesn't resets mana either. I've tried cheating a mana flask in and drink it, which made mana half-red - half-blue and didn't fix any of the problems.
Luckily i had a backup to go back to the point just after casting Lunge. 
My question is, are you aware on how could i possibly un-whew my character? Maybe some NBT editing? I have not found any commands from the mod itself

**Comment by CammiePone** [comment]
You're likely on an old version of the mod, as this has been fixed months ago. Update and die, and things should work again

**Comment by Zarvera** [comment]
I am on 1.21. I've glanced through changelogs for 1.22 and .23 prior to posting but haven't seen anything pertaining to this bug there. 
I'll try anyway in a moment

**Comment by CammiePone** [comment]
I tend to not accurately do changelogs

**Comment by Zarvera** [comment]
That would explain it :)

**Comment by Zarvera** [comment]
Hm, nope. Updated to 1.23, died, but the behaviour persists

**Comment by CammiePone** [comment]
Then it is likely another mod cancelling the regen, or something happened to the regen attribute or base value. Check the config to make sure it isnt set to 0.

Most that is going to happen here is troubleshooting, btw. 1.18 is now out, so 1.17 wont be getting any updates

**Comment by Zarvera** [comment]
ManaCooldown and burnout? They're at 20 and 60 respectively.

**Comment by CammiePone** [comment]
Check the player attribute using the /attributes command

**Comment by Zarvera** [comment]
Mana Regen: 1
Burnout Regen: 1
Mana Lock: 0
These are effective values as i understand, the ones i get through getter, not base\modifiers just in case.

**Comment by CammiePone** [comment]
Alright, then it sounds like something is completely preventing that regen code from running at all. Can I ask you to [enable mixin export](https://fabricmc.net/wiki/tutorial:mixin_export) and send me `class_1657` in PasteBin?

**Comment by Zarvera** [comment]
H-how would one go about doing that? 😅 I'm no coder but i'm willing to help with it if you'll give me a quick rundown

**Comment by CammiePone** [comment]
Depending on the launcher you're using, you just want to add `-Dmixin.debug.export=true` do your VM arguments (you should be able to look up how to for whichever launcher you're using), and then just load up the game and enter a world.

Then go to your modpack folder, and there should be a `.mixin.out` folder near the top, and inside should be a folder titled `net` with a folder titled `minecraft` inside of that, and somewhere in there should be a file called `class_1657`. That class is the PlayerEntity class, and should hopefully tell me what the problem is.

**Comment by Zarvera** [comment]
It's a CurseForge launcher, so it launches through mojangs one. Anyway i've added the argument pre-launch, but there's no net folder. Only audit and class, there's net/minecraft folder inside class folder with a class_1657.class inside but i'm not sure it's the one you want. It's massive

**Comment by CammiePone** [comment]
yea that's the one I want

**Comment by Zarvera** [comment]
Well whew then. :)
https://pastebin.com/61egJvJn

**Comment by CammiePone** [comment]
Try removing the mod Mining Utility? It seems they just for _whatever fucking reason_ cancel the player tick method.

**Comment by Zarvera** [comment]
Sorry, had to scoop out quests for that mod for some time.
Yep! That was that. Everything started working immediately. 
You're awesome, thank you for helping! 😄

**Comment by CammiePone** [comment]
Alright. I would go make a bug report to them about what they're doing. There are two options: don't just cancel the tick method, or lower priority so it's always the last mixin to apply.
