### ISSUE TITLE
[Suggestion] Time bender spell

### ISSUE THREAD

**Issue by w0mby** [CammiePone/Arcanus#33]
Early game a lot of stuffs take time to be made in modded environment and can be frustrating to the evolution for no real added value.
Would be nice to have a spell that could be casted on whatever that the evolution/work is impacted by number of ticks needed. (I guess it's counted in ticks and not in seconds. you get the point :) )
(I think about plant, mob growth but also machine/generator probably?)
You could cast it once to have the evolution going twice fast, or casting the spell twice or three times (ect...) to have the things going faster and faster.  
Limitation of this would be the mana available. 
It's limited in time (when casted it run only x seconds. )
Since Arcanus can be available early game with some exploration it give a meaning of Arcanus in "planning/management" too in addition of all the others things that already exist (damage, teleport, defense,...).
It does not collide with the mods speed upgrade that could be provided since it's limited in time and will probably be used mostly while upgrade are not yet available (due to early game or resource or whatsoever)

**Comment by CammiePone** [comment]
Probably not. I dont know if Ill be updating Arcanus after all, and may instead move plans to a different magic mod entirely.
