### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by shesanicon** [CammiePone/Arcanus#42]
Hello! 

I went to download your Arcanus mod, I looked through the information to see if it required any others mods, it only required fabric so I really didn't need to download anything since I already had fabric, I checked to see if it had 1.18.1 which it did so I downloaded that version. But when I loaded up the game the mod wasn't working, so to test it out, I went into the mod file and tried to delete the mod, (if it completely deleted that means the mod wasn't working, if it didn't delete it would tell me it was currently in use) it completely deleted. I tried to download it again but the same thing happened. 

Please help me if there is a way to fix it, thank you! :)

**Comment by CammiePone** [comment]
Could you send a screenshot of your mods folder?

**Comment by shesanicon** [comment]
![Screenshot 2022-02-22 175626](https://user-images.githubusercontent.com/100245749/155239914-d1c8efda-872b-43fb-aeed-fdcce37ba238.png)

**Comment by CammiePone** [comment]
You need Cloth Config, and I would very much not recommend using Optifine/Optifabric. I would recommend using Sodium and Iris instead.

I've had instances where Optifine/Optifabric just caused certain items from mods to not load at all due to the changes Optifine makes to the Identifier/ResourceLocation class.

**Comment by shesanicon** [comment]
okay thank you, will look into downloading that instead. 
Thank you very much for helping! Have a nice day/night.

**Comment by CammiePone** [comment]
No problem, you too
