### ISSUE TITLE
Arcane barrier, lunge, and config issues

### ISSUE THREAD

**Issue by CornCobDog** [CammiePone/Arcanus#43]
uhh theres a whole buncha problems with my arcanus, ive tried downgrading it to other versions, doesnt seem to work, and the issues are all super peculiar

1. arcane barriers literally do not despawn lol, i have to run a /kill @e[type=arcanus:arcane_barrier] every single time since the barriers just do not go away
2. lunge becomes very overpowered?? i dont know how to explain this but with one lunge spell i shoot 500-1000 blocks forward and just start pinging off random blocks due to high velocity
3. editing the mana cost of spells in arcanus.json or arcanus.json5 does not do anything to affect the game, not after reloading, restarting, reinstalling and even rebooting my pc

im pretty sure most of these are very weird issues, ill be willing to provide videos to show the issues or my mods list for nay wacky incompatibilities. for now, arcanus can just be the fancy display case mod :)

**Comment by CornCobDog** [comment]
also this is just a suggestion but the default mana cost for lunge spells should be doubled or even tripled lmao, those things break early game so much

**Comment by CammiePone** [comment]
Yeah that's way weird. The barriers should disappear after 2 minutes on their own, and lunge being absolutely busted is definitely weird. Not sure why the config isn't working either. List of mods would probably be best.

Also, Arcanus is going to be seeing a complete rewrite, so many of the spells, including lunge, won't exist soon enough anyways.

**Comment by CornCobDog** [comment]
oh lord i have like 300 mods in this is gonna be rough for you mate
its ok if you dont need to find the issue, i can just wait for the arcanus rewrite, that sounds hype :)

mods:
[mods.txt](https://github.com/CammiePone/Arcanus/files/8145684/mods.txt)

**Comment by CammiePone** [comment]
ohno

okay maybe I'll, uh. Just not for now xD

Something you could do if you wanna spend the time is a binary search, since I imagine it's the result of a mod, but idk

![image](https://user-images.githubusercontent.com/16853086/155826351-c817979e-b443-45ae-9e16-692bc489af33.png)

**Comment by CornCobDog** [comment]
yeah i could try that, thanks cammie :)
