### ISSUE TITLE
Crash with Charm

### ISSUE THREAD

**Issue by Alec153** [CammiePone/Arcanus#44]
I have found an incompatibility with Charm. I just tested the two mods together on Minecraft 1.18.2 which resulted in a crash. Arcanus version 1.28, Charm version 4.0.0. I have also reported this to the Charm dev.
[latest.log](https://github.com/CammiePone/Arcanus/files/8240666/latest.log)

**Comment by CammiePone** [comment]
Uhhh from the looks of things, Charm has a mixin that doesn't work on 1.18.2? I don't think this is Arcanus' fault, but it might be. Does Charm load on 1.18.2 on its own?

**Comment by Alec153** [comment]
Yes charm works when Arcanus is disabled.

**Comment by CammiePone** [comment]
I inject into `ClientPlayNetworkHandler#onEntitySpawn`, while they inject into `ClientPlayPacketListener#onEntitySpawn` so I'm not entirely sure why their mixin is failing to inject.

**Comment by CammiePone** [comment]
So just loaded it myself, and it works fine? Not sure why it's crashing for you.

![image](https://user-images.githubusercontent.com/16853086/158080917-01f84e6a-75f1-4b0c-bf67-801ad73e69c3.png)

**Comment by Alec153** [comment]
Strange, the issue still persists for me using the latest versions of fabric api, cloth config, charm, and arcanus with java 17. I wonder what is different between our environments.

**Comment by CammiePone** [comment]
Huh. So it works in my dev environment, but not in a built environment. Yay weird bugs.
