### ISSUE TITLE
Solar Strike & Arcane Barrier don't show up with shaders enabled

### ISSUE THREAD

**Issue by TJ-Pinkerton** [CammiePone/Arcanus#49]
Objects created by spells like Solar Strike & Arcane Barrier don't show up with shaders enabled

![shaderon](https://user-images.githubusercontent.com/61664131/164889858-73e7e492-2e76-4290-8e13-a0cf72f5a2aa.png)
![shaderoff](https://user-images.githubusercontent.com/61664131/164889863-393bb528-b047-442e-8e0c-d5ba29ed8e9b.png)

**Comment by CammiePone** [comment]
Nothing can be done about it. Iris disables modded core shaders
