### ISSUE TITLE
Certain effects are not visible with iris shaders installed

### ISSUE THREAD

**Issue by Alkiasan** [CammiePone/Arcanus#5]
Title, basically. See video here:
https://drive.google.com/file/d/1wSzDahy9Fho6wB9iUCiJFXdrSn1rg8OI/view?usp=sharing

Applies to Arcane Barrier and Solar Strike.

**Comment by CammiePone** [comment]
Yea, that'd be because they use a shader to get the effect they have. It's not something I'm inclined to fix, though.
