### ISSUE TITLE
editing attributes by datapack

### ISSUE THREAD

**Issue by XkrulesVitor** [CammiePone/Arcanus#50]
Hello, sorry for the spelling mistake, I used google translator, I tried to make an arcanus datapack so that they had attributes edited by "playerex" mod, a level rpg mod for minecraft, I tried to modify the values ​​of "baseManaCooldown" and "baseBurnoutCooldown" by datapack and I couldn't, so I tried to modify the values ​​of aura_regen, aura_lock as well but I didn't see any change in the gameplay, my request is that you facilitate the modification of edits of the attributes of your excellent mod

**Comment by CammiePone** [comment]
The mod's getting completely rewritten, so probably not gonna happen. I can look into it for the rewrite though.
