### ISSUE TITLE
dream teleport experience bug

### ISSUE THREAD

**Issue by LargerManZ** [CammiePone/Arcanus#56]
Using dream teleport sometimes removes all of your levels and experience until you collect more, then the previous levels will reappear.

**Comment by CammiePone** [comment]
vanilla bug, yes. there was a pr to fix it but it couldnt be merged. asked the guy who made it to redo the pr but they never did

**Comment by UpcraftLP** [comment]
fixed in https://github.com/CammiePone/Arcanus/commit/1898780f3f140dfff051145413a88fc1cc0fa2d8
