### ISSUE TITLE
Possible issue with Arcanus on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [CammiePone/Arcanus#59]
https://pastebin.com/QQwPNEXe

**Comment by CammiePone** [comment]
try it with just Arcanus before assuming Arcanus and Quilt are incompatible. this is a similar crash to what happens with Arcanus and Charm due to a bad mixin from Charm

given Charm isnt installed, it may very well be another mod

**Comment by Sunconure11** [comment]
I'm sending this crash out to several mods being blamed, so I can hopefully get something found, since I won't have PC access in the next few days

**Comment by CammiePone** [comment]
yeah well it tells us pretty much nothing without actual testing. this kinda error's a bitch. like I said, I've seen the mixin error before and it was Charm's doing, not mine, so if something's fucked, you're gonna have to actually test

**Comment by Sunconure11** [comment]
https://pastebin.com/B7XEWfx3

https://pastebin.com/fe27jZss

Tried without Charm. No dice.

**Comment by CammiePone** [comment]
try with nothing but Arcanus

**Comment by Sunconure11** [comment]
Works fine.
