### ISSUE TITLE
[Bug] Spellcast sound playing at max volume for friend on server, regardless of distance apart

### ISSUE THREAD

**Issue by Cheddar-Goblin** [CammiePone/Arcanus#61]
I'm playing on a Valhelsia server (just me and a friend), and when I cast a spell, he can hear the spell sound full blast, as though he were right next to me, regardless of my distance to him.

The version is Arcanus 1.29 for Minecraft 1.18.2 on Fabric 0.14.8, as part of the Valhelsia: Enhanced Vanilla 1.4.0 Modpack through CurseForge.

If there is anymore information needed, let me know. Thank you!

**Comment by CammiePone** [comment]
Which spell(s) in particular are having this problem?

**Comment by Cheddar-Goblin** [comment]
It's Telekinetic Shock, Magic Missile, and Heal. Those are the only ones I have access to at the moment.
My friend clarified that the distance is not unlimited as I had thought. There just seems to be a very fast ramp up from barely noticeable to full volume (based on the distance). I'll be able to hop on the server tomorrow for testing this out so I can be more accurate with this particular issue.

**Comment by CammiePone** [comment]
ahh I think i know why then. playing sounds in Minecraft is really annoying in how it works, but i should be able to fix it. hopefully.
