### ISSUE TITLE
Strange compat issue with Better End

### ISSUE THREAD

**Issue by Sunconure11** [CammiePone/Arcanus#62]
https://github.com/quiqueck/BetterEnd/issues/52

This issue contains what I used to deduce a conflict between Arcanus and Better End. It seems to happen with larger mod loads, so you might want to go over it yourself.

**Comment by Sunconure11** [comment]
https://gist.github.com/Sunconure11/58d82e41bddef982195cca3cc12ecdd7

Log of interest.

**Comment by Sunconure11** [comment]
If you are using redirects, check this issue out

https://github.com/ArtixAllMighty/HangMan/issues/11

**Comment by CammiePone** [comment]
Sun, you're a modder. you know what redirects look like, just check for them yourself before sending modders on wild goose chases

**Comment by CammiePone** [comment]
I also don't even mixin into class_1088 (aka ModelLoader). that log literally can't be related to Arcanus
