### ISSUE TITLE
Mana bar disappearing randomly

### ISSUE THREAD

**Issue by TeaFloof** [CammiePone/Arcanus#63]
Hello! I'm using the 1.30 Arcanus version for my 1.19 modded fabric server, and the mana bar seems to keep disappearing. I thought at first it was a resource pack issue, so I got rid of the one I was using and it fixed it temporarily until it disappeared again... I'm not really sure what to do.

If you need any more information let me know! Thank you.

**Comment by CammiePone** [comment]
it'll stop showing when it's full and you dont have a wand in your hand. is it disappearing at any other time?

**Comment by TeaFloof** [comment]
When it disappears it won't show up at all. Even when I'm holding my wand and while I'm casting a spell.

**Comment by CammiePone** [comment]
weird. I'll look into it
