### ISSUE TITLE
Can you add my Simplified Chinese translation to the mod?

### ISSUE THREAD

**Issue by VAN-192** [CammiePone/Arcanus#65]
Thank you for making the mod, for which I have made a translation that I hope can be used.
[zh_cn.txt](https://github.com/CammiePone/Arcanus/files/9310724/zh_cn.txt)

**Comment by UpcraftLP** [comment]
Hey, you might want to open a pull request instead for your changes ;)

**Comment by VAN-192** [comment]
I'm sorry I didn't figure out exactly how github works, so I spent an afternoon studying and learning how to use pull requests...
