### ISSUE TITLE
independent sound category

### ISSUE THREAD

**Issue by Bomjus1** [CammiePone/Arcanus#67]
could there be some way to turn down the sound fx of the spells independently of the main game? I love this mod to death, and magic missile is so fun to use early on. but the sound fx for it and some other spells are really grating on the ears.

**Comment by CammiePone** [comment]
yea, I can probably see about adding something in the config. I tend to play at pretty quiet volumes myself (10% max PC volume, and game volume turned down to 25%), and forgot to test it at volumes people are more likely to play at

for now, you can always make a resource pack to turn down the sounds if you need to
