### ISSUE TITLE
Left-over debug stdout print

### ISSUE THREAD

**Issue by Cypher121** [CammiePone/Arcanus#70]
Every time dreamwarp is used, [this line](https://github.com/CammiePone/Arcanus/blob/1.19-dev/src/main/java/dev/cammiescorner/arcanus/core/mixin/PlayerEntityMixin.java#L315) p[rints an STDOUT message to the console. Nothing major so feel free to ignore, but a slight annoyance.

**Comment by CammiePone** [comment]
oh lmao, well good news is I'm currently rewriting Arcanus because I feel like making a new version of it to allow for more than 8 spells, while still retaining the simplicity of the mod

**Comment by UpcraftLP** [comment]
fixed in https://github.com/CammiePone/Arcanus/commit/4b0a3a341cc0d8d986f7283332685fc9393d9a91
