### ISSUE TITLE
Mixin crash 2: More annoying and cryptic than ever!

### ISSUE THREAD

**Issue by Sunconure11** [CammiePone/Arcanus#74]
https://pastebin.com/4m7T5LHy

I had turned off several mods mentioned, but I just kept getting weirder and weirder errors all blaming mixins, and are obviously not the true culprit. Pretty sure BA+ doesn't touch the same stuff as this mod FFS. Same with Terrablender.

**Comment by CammiePone** [comment]
have you tried disabling supplementaries

**Comment by Sunconure11** [comment]
I did. I’ll try some more ideas tomorrow, I’m in bed.

**Comment by Sunconure11** [comment]
Trying to look into something relating to OwO-lib, as it was mentioned in the error, but whatever mod is still attempting to use it is throwing a fit, even with all mods using it seemingly pulled.

**Comment by Sunconure11** [comment]
https://pastebin.com/f7XpcZdR

**Comment by Sunconure11** [comment]
Still sorting through mods. It wants to blame one mod after another, when it is clear none of these are at fault.

**Comment by Sunconure11** [comment]
https://pastebin.com/AxrMCv1L

**Comment by Sunconure11** [comment]
https://pastebin.com/BUSi5DPW

**Comment by Sunconure11** [comment]
I'll try other approaches if I can think of them. Kept turning off mod after mod and just got weirder and weirder crashes.

**Comment by Sunconure11** [comment]
https://gist.github.com/Sunconure11/9dc6a634526e9d29f0f949331b955904 Here's a full log, including the crash, just in case something sticks out

**Comment by DanMeadWasTaken** [comment]
So honestly, A trick I've found in my time making a couple packs. Is literally turn everything off, try running the mod by itself. Then if that works, Slowly turn on groupings of mods until you hit a group that triggers a crash, then one by one going through until you find which of the group caused it. 

I've had some weird ones before, like the time meteor client and sandwhichable <back in 1.16.5> were causing a crash together. (Back then I liked the Idea of using something like meteor client in my packs, but later found the opness kinda ruined the fun for me).

Anyway- Back to topic, It might seems like it'll take ages, and sometimes It can feel like it, but- Especially in my case using tons of mods- Ya just gotta brute force it. I am currently as we speak, testing my own mods by first doing the A's, then turning those off and doing the B's and so on and so forth. Now having to turn on the A's then turn on the B's then the C's and that's as far as I got before coming across a conflict between mods and having to use the aforementioned method to track it down.

Edit: after thought, when running all the mods at once, and running into an issue- It's gonna spit out like 20 or more different possible causes till it either gets to the one actually causing the issue, or just stops making sense... So the aforementioned method of brute forcing can generally save alot of headaches, although mostly for bigger packs.

**Comment by DanMeadWasTaken** [comment]
Oh- And after looking at that latest log, Firstly, I've found (Just from testing with quilt ealier) Some mods don't actually work in quilt for various reasons. Although in your case, If you're using multimc, look for the mod which shows ${version} as it's version number.... I ran into this literally earlier when I was tryna run a quilt mod in fabric. It also helps that this shows up in your log, turn off whatever mod has that as it's version number, and It'll either fix it, or get you one step closer

**Comment by Sunconure11** [comment]
I had been doing a form of a binary search to find the culprit, but I got too exhausted mentally because nothing was working

**Comment by Sunconure11** [comment]
[18:23:28] [Render thread/ERROR]: Critical injection failure: LVT in net/minecraft/class_634::method_11112(Lnet/minecraft/class_2604;)V has incompatible changes at opcode 100 in callback arcanus.mixins.json:client.ClientPlayNetworkHandlerMixin from mod arcanus->@Inject::onEntitySpawn(Lnet/minecraft/class_2604;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1299;)V.
 Expected: [Lnet/minecraft/class_1299;]
    Found: []
Available: []


This seems of interest

**Comment by Sunconure11** [comment]
It seems you reported a similar error in the past, but with Charm @CammiePone. I can also confirm that said error still persists with Charm.

https://github.com/svenhjol/Charm/issues/747

It is something that is conflicting with `onEntitySpawn`. I will look around for more info.

**Comment by Sunconure11** [comment]
https://gist.github.com/Sunconure11/06d642302ac3186e6b54ed43c83bc76b WTF?

https://gist.github.com/Sunconure11/010cecace842335a308bed75d6106ebf Bruh there's no way I'm going to turn off every mod using Architectury

**Comment by Sunconure11** [comment]
I've found the culprit. Or rather, several potential ones.

The mod at fault is...

One of the following:

Due to the nature of the error being caused by something using Architectury, I can't pinpoint further. However, I got the game running.

Earth2Java
Biome Makeover
Minecraft Story Mode Armors
KubeJS
Assorted Discoveries
Storage Cabinet

The Corners, while not using Architectury, may also be to blame.

https://gist.github.com/Sunconure11/fb9c8da7e39a25322f0ac164774a371a

I found an error relating to something by Shedaniel after disabling the mods that use Architectury, but GitHub refused to take a Gist in with the error.

Edit: None of these mods are at fault.

**Comment by Sunconure11** [comment]
At this point, the errors are getting more and more vague, but I do see one thing that is pretty common in all of the errors, mods using cardinal components.

Whatever `class_634` corresponds to is mentioned a lot as well.

**Comment by Sunconure11** [comment]
Going over a previous error... yeah, I encountered this before. I tried some other ways of searching but nothing came up.

I tried several binary searches but none led to the mod in question.

**Comment by DanMeadWasTaken** [comment]
Honestly, could be the use of quilt loader. In my case I'm using fabric, as I had tried quilt, but not all fabric mods seem to be compatible with the quilt loader. Could try the same pack on fabric? Although, you'd lose any mods that were made explicitly for quilt

**Comment by Sunconure11** [comment]
I’m not convinced it’s Quilt. I reported a similar error on Fabric in the past.
