### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by DanMeadWasTaken** [CammiePone/Arcanus#75]
Due to NotEnoughCrashes supressing the crash, It kinda just kept repeatedly crashing and loading up in a loop, making the log look a bit janky, but arcanus' missing texture is the one thing constantly repeated everytime it crashed

https://paste.ee/p/zR8oa <-- Crash log uploaded from multimc

Edit: as an afterthought looking at the log myself, I figured I'd help speed up the process by just pasting the specific thing it kept spitting out related to arcanus.

java.lang.IllegalStateException: Redundant texture list for particle arcanus:magic_missile

**Comment by DanMeadWasTaken** [comment]
Actually scratch the comment that this used to be- turns out this mod and another one were both giving this same issue, and once removed they both stopped giving this issue... I'm still looking further into it as i type this though to figure out which mods might be conflicting with what

**Comment by DanMeadWasTaken** [comment]
I feel stupid, After trying each mod in turn. It turned out one mod needed cardinal-components and wasn't telling me as much, but once it was added, the overflow crash stopped happening all together

**Comment by Sunconure11** [comment]
Did your error mention something about cardinal-components-scoreboard by any chance at one point?

**Comment by Sunconure11** [comment]
If so, see if you can find any shared mods that might be crashing with us two

https://github.com/CammiePone/Arcanus/issues/74
