### ISSUE TITLE
What kind of damage do you do? Compatible with "magic dmg"?

### ISSUE THREAD

**Issue by notIkibo** [CammiePone/Arcanus#79]
RPGstats or PlayerEx gives you buffs like "Mage DMG increase". It doesn't seem to be compatible. Or is it? It should be, so more mage related things connect together. I feel like Magic Missle is also not affected by any dmg increase or decrease, but Solar Strike is. Why is that? And can you look into that?

**Comment by CammiePone** [comment]
that's because only Solar Strike is a unique damage type. i most likely wont make any changes to current Arcanus, as im working on a sequel, Arcanus: Continuum
https://github.com/CammiePone/Arcanus/blob/1.19-dev/src/main/java/dev/cammiescorner/arcanus/core/registry/ModDamageSource.java

**Comment by notIkibo** [comment]
Wait what?? A sequel? You're godsent and I'm hyped. That's wonderful news (when does it come out :o), but I somehow really want to know how certain effects interact with certain damage types. E.g. magic missle and solar strike. What defines them?
