### ISSUE TITLE
Arcanus-1.10 breaking REI, its stuck on final load. 

### ISSUE THREAD

**Issue by frikinjay** [CammiePone/Arcanus#8]
arcanus-1.10 is breaking REI, its stuck on final load. Nothing happens when you click on the recipes. I've seen this issue before and in MCDoom Mod's case it was nbtcrafting though i am not sure if youre even using nbtcrafting. Both arcanus and REI are on the latest release.

**Comment by CammiePone** [comment]
Okay so that was Arcanus' fault... I actually don't know why though, I'm not touching any of the recipes in any weird way. You can fix it by reloading the plugins in the options menu, but I have no clue why it's happening in the first place.

**Comment by CammiePone** [comment]
Never mind, I do know what's causing it, and I accidentally fixed it while trying to fix another problem. Release will happen shortly, just have another problem that might be Arcanus, might not, that I wanna iron out rq.
