### ISSUE TITLE
Permission to port spells to Spell Engine for Wizards compatibility

### ISSUE THREAD

**Issue by Frontear** [CammiePone/Arcanus#81]
I'm a user from Medieval Minecraft. Recently we've had a discussion on whether we want to replace one of our magic mods with a new Wizards mod. Arcanus was mentioned in the discussion, and something that users agreed on was that the spells Lunge and Dreamwarp are an integral part of the modpack experience. 

One of the lead devs of the modpack suggested that maybe its a good idea to ask Arcanus dev for permission to port over the spells to a custom [Spell Engine](https://www.curseforge.com/minecraft/mc-mods/spell-engine), which is used by the [Wizards](https://www.curseforge.com/minecraft/mc-mods/wizards) mod. Overall, it adds a lot more things, but would be missing something critical.

Now you may be wondering, why not just keep Arcanus? Something to note is that we also use another mod that adds magic and spells. Users already express confusion at the two, so having a third alongside the two would cause a lot of confusion.

On to the main part of the message: May we have your permission to port over some of the spells to the Spell Engine? We are willing to offer credit rightfully to you and your mod for the idea and logic behind the spells. It would overall be a nice move for the modpack.

**Comment by CammiePone** [comment]
im fine with you using my code for the spells, under just one stipulation: I get a share of the points from the mod based on the number of spells being taken from Arcanus vs the total number of spells in Spell Engine (i.e. if you port two spells from Arcanus to Spell Engine, and Spell Engine had a total of 50 spells, I'd want a 4% cut)

however, you are free to just. take the ideas. nothing I can do about that, only thing I own is the specific code. choice is up to yall tho

**Comment by Frontear** [comment]
To clarify two points, first is that Spell Engine is a data-driven mod. Effectively, spells can be added as datapacks. This would lead into the second point, that the spell would not be a direct one-to-one copy of your code, but rather a reimagination/reimplementation of it inspired by Arcanus spells.

I'd need to directly speak with the lead dev in regards to the contribution points. Please feel free to join the [LunaPixelStudios discord](https://discord.gg/lunapixel) if you'd like to speak with us directly, including the lead dev and the dev of Wizardry/Spell Engine, including discussing the contribution points.
