### ISSUE TITLE
No spells

### ISSUE THREAD

**Issue by NebulousCreation** [CammiePone/Arcanus#82]
I'm currrently playing with the medieval minecraft modpack and can't seem to find any of the Arcanus spells. I've been playing in this world for a while now and have been actively searching villages for spell books with no luck so I checked REI and they don't appear there either. The only Items that show up in REI are the wands, mana flasks, bookshelf, and display case. I even tried to spawn one in with the /give command but again the only items there were the ones I listed. This mod was on a server I used to play with my friends and I loved it so I'd hate to not be able to use it now for some reason. Any suggestions on what I can do?

**Comment by CammiePone** [comment]
so, its not showing up in REI because the books are just vanilla books with additional nbt. you can use commands to get them if they arent spawning, but if they arent spawning that means something is replacing the default structures

**Comment by NebulousCreation** [comment]
That'd probably be one of the other mods in the pack then. would you mind telling me what the commands are I could use?

**Comment by CammiePone** [comment]
iirc it's just /spell or maybe its /spellbook or something like that. it's been a hot minute since I've messed with it since ive been working on the sequel to the mod

**Comment by NebulousCreation** [comment]
Fantastic! Worked like a charm :) Thanks for the help and for making such a great mod, keep up the awesome work!
