### ISSUE TITLE
Question about tweaking damage

### ISSUE THREAD

**Issue by TheGeorginator** [CammiePone/Arcanus#85]
Is it possible to tweak the damages for certain spells? I want to nerf Solar Strike to make it more balanced for my friend's server. I looked in the configs, but all I saw was mana cost, etc... No damage. Is this something I would have to make a fork of the mod for? And if so, am I allowed to do that?

**Comment by CammiePone** [comment]
you would have to fork it, yes, but only if you're using it privately. you cant upload it somewhere for anyone to download
