### ISSUE TITLE
[Version Support] Support for 1.19.2?

### ISSUE THREAD

**Issue by RandomGgames** [CammiePone/Arcanus#86]
Could we get a 1.19.2 version of this mod if it wouldn't be too much trouble for you? Would really appreciate it!

**Comment by Xiribidus** [comment]
https://www.curseforge.com/minecraft/mc-mods/arcanus/files/3877921
Does this one not work?

**Comment by RandomGgames** [comment]
Oh that works, my eyes and brain just don't apparently. My apologies! I am working on a minecraft mod manager, was trying to figure out why some mods weren't downloading, must have made a report for the wrong mod. MB! What was the right mod then....?

**Comment by RandomGgames** [comment]
OH, no, I wasn't mistaken, I went through the mods list again. It was for Modrinth. 1.19.2 isn't on there.
https://modrinth.com/mod/arcanus/versions

Never the less my brain still doesn't work apparently :P

**Comment by Xiribidus** [comment]
https://modrinth.com/mod/arcanus/version/1.30
its this one, might not say 1.19.2 specifically but its the same mod version as in the cf link above so it should work

**Comment by RandomGgames** [comment]
This is probably more of a me issue, but that's exactly the problem. I'm working on a mod manager that, given a mod URL and a game version, looks through a list of mods you define and it checks for updates and downloads them automatically. It cannot download the latest version for 1.19.2 automatically because it can't see that it's compatible with 1.19.2. It's not set in the versions. If you're interested in taking a look, it's a repo on my account called RMMUD. Look at the DEV branch.

**Comment by triphora** [comment]
I've added it as a Modrinth admin.

**Comment by UpcraftLP** [comment]
thank you @triphora ^^
