### ISSUE TITLE
Incompatible mixin from Arcanus

### ISSUE THREAD

**Issue by Sunconure11** [CammiePone/Arcanus#87]
https://gist.github.com/Sunconure11/0b1ba0a3a7259e3879566e6bf446dfa9

**Comment by Sunconure11** [comment]
I realize I reported this a few times in the past, but has it been considered to look at this mod itself to see if it is crapping out with another mod? I keep running into this at complete random and have no clue how to solve it. It is one strange heisenbug.

**Comment by CammiePone** [comment]
this is 1.19.2, it wont be fixed
