### ISSUE TITLE
[1.29.1 - 1.18.2] weird Fabric Loader limitation

### ISSUE THREAD

**Issue by MSandro** [CammiePone/Arcanus#90]
Arcanus 1.29 worked great with Fabric Loader 0.14.21, but v1.29.1 is restricted to <= 0.14.14, why???
![image](https://github.com/CammiePone/Arcanus/assets/10937159/3e1fea8e-4aae-400e-aa4d-cf312f8d4dbd)

**Comment by UpcraftLP** [comment]
*Something* broke in 0.14.15+ and I haven't had time to investigate it further.

**Comment by UpcraftLP** [comment]
Fixed in [v1.29.2](https://www.curseforge.com/minecraft/mc-mods/arcanus/files/4734997)
