### ISSUE TITLE
Additional Books for fillable bookshelf

### ISSUE THREAD

**Issue by wildsided1** [CammiePone/Arcanus#92]
Hi,

I am using the 1.19.2 version of the mod and would like to use the fillable bookshelf to store all the various books from the mods in the mod pack (AOF6). Some of the books are compatible and will go into an available slot in the bookshelf while others, the spectrum guidebook for example, will not.

Is there an easy way to books to the list of books that the shelf will accept? Or would that require a lot of work?

Thanks for your time.

**Comment by CammiePone** [comment]
it's just a tag iirc. you can just make a data pack 
https://github.com/CammiePone/Arcanus/blob/1.19-dev/src/main/resources/data/c/tags/items/books.json
